server:
  port: 9000

spring:
  application:
    name: picture-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  healthcheck:
    enabled: true
